const GET_LIMIT_LOWER_BOUND = 1;
const GET_LIMIT_UPPER_BOUND = 500;
const GET_OFFSET_LOWER_BOUND = 0;
const GET_OFFSET_UPPER_BOUND = 1000000 - GET_LIMIT_UPPER_BOUND;

const INVITATIONS_ITEMS_LIMIT = 100;
const GET_INVITATIONS_LIMIT_LOWER_BOUND = 1;
const GET_INVITATIONS_LIMIT_UPPER_BOUND = 25;
const GET_INVITATIONS_OFFSET_LOWER_BOUND = 0;
const GET_INVITATIONS_OFFSET_UPPER_BOUND = INVITATIONS_ITEMS_LIMIT;

const GET_ALL_FOLDERS_LIMIT_LOWER_BOUND = 1;
const GET_ALL_FOLDERS_LIMIT_UPPER_BOUND = 1000;

export default {
  FILES: {
    GET: {
      LIMIT: {
        LOWER_BOUND: GET_LIMIT_LOWER_BOUND,
        UPPER_BOUND: GET_LIMIT_UPPER_BOUND,
      },
      OFFSET: {
        LOWER_BOUND: GET_OFFSET_LOWER_BOUND,
        UPPER_BOUND: GET_OFFSET_UPPER_BOUND,
      },
    },
  },
  FOLDERS: {
    GET: {
      ALL: {
        LIMIT: {
          LOWER_BOUND: GET_ALL_FOLDERS_LIMIT_LOWER_BOUND,
          UPPER_BOUND: GET_ALL_FOLDERS_LIMIT_UPPER_BOUND,
        },
      },
    },
  },
  SHARING: {
    GET: {
      INVITATIONS: {
        LIMIT: {
          LOWER_BOUND: GET_INVITATIONS_LIMIT_LOWER_BOUND,
          UPPER_BOUND: GET_INVITATIONS_LIMIT_UPPER_BOUND,
        },
        OFFSET: {
          LOWER_BOUND: GET_INVITATIONS_OFFSET_LOWER_BOUND,
          UPPER_BOUND: GET_INVITATIONS_OFFSET_UPPER_BOUND,
        },
      },
    },
  },
};
