// TODO: extract this category → extensions mapping to a shared package
// (e.g. @internxt/sdk) so drive-web (src/app/drive/types/file-types.ts) and
// this backend stop maintaining duplicated copies.
export enum FileCategory {
  Folder = 'folder',
  Audio = 'audio',
  Code = 'code',
  Csv = 'csv',
  Figma = 'figma',
  Image = 'image',
  Pdf = 'pdf',
  Ppt = 'ppt',
  Txt = 'txt',
  Video = 'video',
  Word = 'word',
  Xls = 'xls',
  Xml = 'xml',
  Zip = 'zip',
}

export const FILE_CATEGORY_EXTENSIONS: Record<FileCategory, string[]> = {
  [FileCategory.Folder]: [],
  [FileCategory.Audio]: [
    'aa',
    'aac',
    'aax',
    'ac3',
    'act',
    'aiff',
    'alac',
    'amr',
    'ape',
    'au',
    'awd',
    'dss',
    'dts',
    'dvf',
    'flac',
    'gsm',
    'iklax',
    'ivs',
    'm4a',
    'm4b',
    'm4p',
    'mmf',
    'mogg',
    'mp2',
    'mp3',
    'mpc',
    'msv',
    'nmf',
    'ogg',
    'oga',
    'opus',
    'ra',
    'rm',
    'rf64',
    'sln',
    'tta',
    'voc',
    'vox',
    'wav',
    'wma',
    'wv',
    'weba',
    '8svx',
    'cda',
  ],
  [FileCategory.Code]: [
    'c',
    'h',
    'cpp',
    'c++',
    'cc',
    'cxx',
    'hpp',
    'h++',
    'hh',
    'hxx',
    'cob',
    'cpy',
    'cs',
    'cmake',
    'coffee',
    'css',
    'less',
    'sass',
    'scss',
    'f',
    'for',
    'f77',
    'f90',
    'aspx',
    'html',
    'hmn',
    'java',
    'jsp',
    'js',
    'ts',
    'json',
    'jsx',
    'kt',
    'm',
    'nb',
    'php',
    'php3',
    'php4',
    'php5',
    'phtml',
    'build',
    'bzl',
    'py',
    'pyw',
    'rb',
    'sql',
    'vue',
    'yaml',
    'yml',
  ],
  [FileCategory.Csv]: ['csv'],
  [FileCategory.Figma]: ['fig'],
  [FileCategory.Image]: [
    'tif',
    'tiff',
    'bmp',
    'heic',
    'jpg',
    'jpeg',
    'gif',
    'png',
    'eps',
    'raw',
    'cr2',
    'nef',
    'orf',
    'sr2',
    'webp',
  ],
  [FileCategory.Pdf]: ['pdf'],
  [FileCategory.Ppt]: ['ppt', 'pptx', 'pptm'],
  [FileCategory.Txt]: [
    'txt',
    'text',
    'md',
    'rst',
    'adoc',
    'conf',
    'def',
    'list',
    'lock',
    'toml',
    'ini',
    'cfg',
    'properties',
    'json',
    'jsonc',
    'tsv',
    'tsx',
    'jsx',
    'ts',
    'js',
    'mjs',
    'cjs',
    'go',
    'rs',
    'swift',
    'sh',
    'bash',
    'zsh',
    'ps1',
    'bat',
    'cmd',
    'htm',
    'html',
    'log',
    'patch',
    'diff',
  ],
  [FileCategory.Video]: [
    'webm',
    'mkv',
    'vob',
    'ogv',
    'ogg',
    'drc',
    'avi',
    'mts',
    'm2ts',
    'mov',
    'qt',
    'wmv',
    'yuv',
    'rm',
    'rmvb',
    'viv',
    'asf',
    'amv',
    'mp4',
    'mpg4',
    'm4v',
    'mpg',
    'mpeg',
    'mpe',
    'mpv',
    'm2v',
    'svi',
    '3gp',
    '3g2',
    'mxf',
    'roq',
    'nsv',
    'flv',
    'f4v',
    'f4p',
    'f4a',
    'f4b',
  ],
  [FileCategory.Word]: ['doc', 'docx'],
  [FileCategory.Xls]: ['xls', 'xlsx'],
  [FileCategory.Xml]: ['xml', 'xsl', 'xsd', 'svg'],
  [FileCategory.Zip]: ['zip', 'zipx'],
};

export function resolveCategoriesToExtensions(
  categories: FileCategory[],
): string[] {
  const extensions = categories.flatMap(
    (category) => FILE_CATEGORY_EXTENSIONS[category],
  );
  return [...new Set(extensions)];
}
