module.exports = {
  development: {
    dialect: 'postgres',
    host: 'localhost',
    database: 'xCloud',
    username: 'admin',
    password: 'example',
    port: 5432,
    logging: true,
    dialectOptions: {
      keepAlive: 20000,
      statemenet_timeout: 4000,
    },
    pool: {
      maxConnections: Number.MAX_SAFE_INTEGER,
      maxIdleTime: 30000,
      max: 20,
      min: 0,
      idle: 20000,
      acquire: 20000,
    },
  },
  test: {
    dialect: 'postgres',
    host: process.env.RDS_HOSTNAME,
    database: process.env.RDS_DBNAME,
    username: process.env.RDS_USERNAME,
    password: process.env.RDS_PASSWORD,
    port: process.env.RDS_PORT,
    logging: true,
    dialectOptions: {
      keepAlive: 20000,
      statemenet_timeout: 4000,
    },
    pool: {
      maxConnections: Number.MAX_SAFE_INTEGER,
      maxIdleTime: 30000,
      max: 20,
      min: 0,
      idle: 20000,
      acquire: 20000,
    },
  },
  production: {
    host: process.env.RDS_HOSTNAME,
    database: process.env.RDS_DBNAME,
    username: process.env.RDS_USERNAME,
    password: process.env.RDS_PASSWORD,
    dialect: 'postgres',
    dialectOptions: {
      keepAlive: 20000,
      statemenet_timeout: 4000,
    },
    pool: {
      maxConnections: Number.MAX_SAFE_INTEGER,
      maxIdleTime: 30000,
      max: 20,
      min: 0,
      idle: 20000,
      acquire: 20000,
    },
  },
};
