export interface UserAttributes {
  id: number;
  userId: string;
  name: string;
  lastname: string;
  email: string;
  username: string;
  bridgeUser: string;
  password: string;
  mnemonic: string;
  rootFolderId: number;
  rootFolder?: any;
  hKey: Buffer | string;
  secret_2FA: string;
  errorLoginCount: number;
  isEmailActivitySended: number;
  referralCode: string;
  referrer: string;
  syncDate: Date;
  uuid: string;
  lastResend: Date;
  credit: number;
  welcomePack: boolean;
  registerCompleted: boolean;
  backupsBucket: string;
  sharedWorkspace: boolean;
  avatar: string;
  lastPasswordChangedAt?: Date;
  tierId?: string;
  emailVerified: boolean;
  updatedAt?: Date;
  createdAt?: Date;
  registrationRecord?: string;
}
