version: '3.9'

services:
  drive-server:
    build:
      context: ../
      dockerfile: infrastructure/development.Dockerfile
    container_name: drive-server
    ports:
      - 3004:3004
    depends_on:
      - drive-database
    volumes:
      - ../src:/usr/app/src
    networks:
      - internxt

  drive-database:
    image: postgres:15
    container_name: drive-database
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./database-init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: xCloud
    networks:
      - internxt

  redis:
    image: redis:latest
    container_name: drive-server-redis
    restart: always
    networks:
      - internxt

networks:
  internxt:
    name: internxt
