name: build & deploy
on: ["pull_request"]
jobs:
  build:
    if: ${{ !contains(github.event.pull_request.title, 'feature-deployment') }}
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
        with:
          registry-url: 'https://npm.pkg.github.com'
      - run: echo "registry=https://registry.yarnpkg.com/" > .npmrc
      - run: echo "@internxt:registry=https://npm.pkg.github.com" >> .npmrc
      # You cannot read packages from other private repos with GITHUB_TOKEN
      # You have to use a PAT instead https://github.com/actions/setup-node/issues/49
      - run: echo //npm.pkg.github.com/:_authToken=${{ secrets.PERSONAL_ACCESS_TOKEN }} >> .npmrc
      - run: echo "always-auth=true" >> .npmrc
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push to drive-server-wip
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./development.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/drive-server-wip:pr-${{ github.event.number }}-${{ github.sha }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: develop
    steps:
      - uses: actions/checkout@master
      - name: Create feature deployment
        uses: steebchen/kubectl@v2.0.0
        with: # defaults to latest kubectl binary version
          config: ${{ secrets.KUBE_CONFIG_DATA_DEVELOPMENT }}
          version: v1.22.2
          command: create deployment drive-server-wip-${{ github.event.number }} --image=drive-server-wip:pr-${{ github.event.number }}-${{ github.sha }}
      # - name: Update drive-server-wip image
      #   uses: steebchen/kubectl@v2.0.0
      #   with: # defaults to latest kubectl binary version
      #     config: ${{ secrets.KUBE_CONFIG_DATA_DEVELOPMENT }}
      #     version: v1.22.2
      #     command: set image --record deployment/drive-server-wip-${{ github.event.number }} drive-server-wip-${{ github.event.number }}=${{ secrets.DOCKERHUB_USERNAME }}/drive-server-wip-${{ github.event.number }}:${{ github.sha }}
      - name: Verify drive-server deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA_DEVELOPMENT }}
          version: v1.22.2 # specify kubectl binary version explicitly
          command: rollout status deployment/drive-server-wip-${{ github.event.number }}