name: Deploy feature
on:
  pull_request:
  workflow_dispatch:
    inputs:
      drive-server-branch:
        type: string
        description: Insert drive server branch to connect to
jobs:
  retrive-pr:
    permissions:
      security-events: write
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: | 
          PR_JSON=$(gh pr view https://github.com/internxt/drive-server/pull/324  --json headRefName,state,headRepository,number)
          REPOSITORY=$(jq -r '.headRepository.name' <<< "$PR_JSON")
          if [ $REPOSITORY != 'drive-server' ];
          then
            echo "Invalid PR. Plase insert a drive-server pr"
            exit 1
          fi
          REF=$(jq -r '.headRefName' <<< "$PR_JSON")
          gh workflow run run-tests.yml --repo internxt/drive-server --ref "$REF"
