name: Code coverage
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  check:
    permissions:
      contents: read
      packages: read
      pull-requests: write
    name: Pre-merge checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}

      - name: Run check
        run: yarn danger ci
        env:
          DANGER_GITHUB_API_TOKEN: ${{ github.token }}