name: Code coverage
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  check:
    name: Pre-merge checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v1
      - name: Danger
        uses: danger/danger-js@9.1.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}