name: Run e2e tests
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    environment:
      name: development
    env:
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      SENDGRID_MODE_SANDBOX: true
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'

      # We should see why permissions field is not doing the job. This should be removed
      - run: echo "registry=https://registry.yarnpkg.com/" > .npmrc
      - run: echo "@internxt:registry=https://npm.pkg.github.com" >> .npmrc
      # You cannot read packages from other private repos with GITHUB_TOKEN
      # You have to use a PAT instead https://github.com/actions/setup-node/issues/49
      - run: echo //npm.pkg.github.com/:_authToken=${{ secrets.PERSONAL_ACCESS_TOKEN }} >> .npmrc
      - run: echo "always-auth=true" >> .npmrc

      - name: Setup environment
        uses: hoverkraft-tech/compose-action@b716db5b717cb9b81e391fe638e5aceaa2299e43
        with:
          compose-file: './infrastructure/docker-compose.yml'

      - name: Install dependencies
        run: yarn

      - name: Run e2e tests
        run: yarn migrate:test && yarn run db:seed:test:all && yarn run test:e2e
